dist: trusty
sudo: required

language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

go_import_path: github.com/smira/aptly

addons:
  apt:
    packages:
    - python-virtualenv
    - graphviz

env:
  global:
    - secure: "YSwtFrMqh4oUvdSQTXBXMHHLWeQgyNEL23ChIZwU0nuDGIcQZ65kipu0PzefedtUbK4ieC065YCUi4UDDh6gPotB/Wu1pnYg3dyQ7rFvhaVYAAUEpajAdXZhlx+7+J8a4FZMeC/kqiahxoRgLbthF9019ouIqhGB9zHKI6/yZwc="
    - secure: "EcCzJsqQ3HnIkprBPS1YHErsETcb7KQFBYEzVDE7RYDApWeapLq+r/twMtWMd/fkGeLzr3kWSg7nhSadeHMLYeMl9j+U7ncC5CWG5NMBOj/jowlb9cMCCDlmzMoZLAgR6jm1cJyrWCLsWVlv+D0ZiB0fx4xaBZP/gIr9g6nEwC8="
    - secure: "OxiVNmre2JzUszwPNNilKDgIqtfX2gnRSsVz6nuySB1uO2yQsOQmKWJ9cVYgH2IB5H8eWXKOhexcSE28kz6TPLRuEcU9fnqKY3uEkdwm7rJfz9lf+7C4bJEUdA1OIzJppjnWUiXxD7CEPL1DlnMZM24eDQYqa/4WKACAgkK53gE="
    - NO_FTP_ACCESS: "yes"
    - BOTO_CONFIG: /dev/null
before_install:
  - env
  - virtualenv system/env
  - . system/env/bin/activate
  - pip install six packaging appdirs
  - pip install -U pip setuptools
  - pip install -r system/requirements.txt
  - make version
install:
  - make prepare

script: make travis

matrix:
    allow_failures:
        - go: master

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/c691da114a41eed6ec45"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
